# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name=b'\xe9\xa2\x98\xe7\x9b\xae')),
                ('create_time', models.DateTimeField(verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('deleted', models.BooleanField(verbose_name=b'\xe5\x88\xa0\xe9\x99\xa4\xe7\x8a\xb6\xe6\x80\x81')),
                ('pub_name', models.CharField(max_length=10, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe4\xba\xba')),
                ('content', models.CharField(max_length=20000, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe5\x86\x85\xe5\xae\xb9')),
            ],
        ),
    ]
